### ISSUE TITLE
RS600

### ISSUE THREAD

**Issue by Symbian9** [clbr/radeontop#129]
Does it usable for ATI Radeon 1250 Xpress?

**Comment by clbr** [comment]
Probably. Try it.

**Comment by lorn10** [comment]
Yes, this comes late but nope, this will unfortunately not work because the RS600 aka Radeon [Xpress 1250](https://en.wikipedia.org/wiki/AMD_690_chipset_series#Radeon_Xpress_1250) IGP is in the end "a version of the 690G IGP chipset for Intel processors" which is itself a **R400** derivative.

However, it would be really great if radeontop could be expanded regarding the **R500** series. The corresponding Mesa drivers are still maintained also in 2022 by the Mesa devs, volunteers and enthusiasts. So maybe there exist a chance to implement support at least for this pre-R600 generation in radeontop on Linux. :wink:

**Comment by clbr** [comment]
There's an existing ticket about R500 support, you'll find the long details there. In short: R500 exposes much less info, doesn't make sense to support in radeontop, may not make sense even in a standalone app.

**Comment by lorn10** [comment]
Thanks @clbr, I have found the corresponding ticket #20. :+1: 

So there exist(ed) a non-official radeontop build which works with a RV515 aka Radeon X1300 but with reduced information? My retro Apple iMac 5,1 computer comes with a RV530 based Radeon X1600 GPU. Maybe the mentioned experimental build is working also with this R500 based GPU. :wink: 

Maybe I should simply ping @bralston7 and ask if he can make 7 years later a standalone AppImage build of his special radeontop version. It will be interesting to know if this works also with the present-day **r300g** Gallium driver while in the past there was previously only the "classic" version r300.

Any further discussion should be happen in #20. This here can be closed I think...
