### ISSUE TITLE
radeon 5870m support

### ISSUE THREAD

**Issue by adrenochrome25** [clbr/radeontop#25]
Hello,

I use a radeon 5870m with catalyst 15.201 on Ubuntu 12.04LTS(3.13.0-67-generic), but radeontop report only "0.00%" values for each entry.
i noticed several things : 

- warning "Kernel too old for VRAM reporting."
-> should it explain all zeroes ?

- radeontop report GPU as "JUNIPER"(0x68a0) but "5870 Broadway XT" should be "CYPRESS" ...
->in "r600_pci_ids.h", i tried to change the entry "0x68A0" from "JUNIPER" to "CYPRESS" but i still get only "0.00%" values

any advice on what's going wrong or how to debug ?

thanks in advance,
regards,

**Comment by clbr** [comment]
Oh, regarding the name, Juniper seems correct:
https://en.wikipedia.org/wiki/Comparison_of_AMD_graphics_processing_units

Mobility 5870 is a Juniper, desktop 5870 is Cypress.

**Comment by clbr** [comment]
Did Github just delete my older comment? Anyway, here it is.

The kernel warning will only affect the VRAM line, not the other ones.
Likewise, the device name doesn't really matter, it is cosmetic.

Is this a laptop with only one GPU, or several?

When using the proprietary driver, radeontop must use the /dev/mem
codepath. At the end of init_pci(), before the return, add
printf("use ioctl %u\n", use_ioctl);

and let me know the result. The /dev/mem option was disabled in more
recent Ubuntu kernels, but since you're running older Ubuntu, it should
still work.

**Comment by clbr** [comment]
The kernel warning will only affect the VRAM line, not the other ones.
Likewise, the device name doesn't really matter, it is cosmetic.

Is this a laptop with only one GPU, or several?

When using the proprietary driver, radeontop must use the /dev/mem
codepath. At the end of init_pci(), before the return, add
printf("use ioctl %u\n", use_ioctl);

and let me know the result. The /dev/mem option was disabled in more
recent Ubuntu kernels, but since you're running older Ubuntu, it should
still work.

**Comment by adrenochrome25** [comment]
it's a MSI GX740, it's the only/main GPU

printf("use ioctl %u\n", use_ioctl);
use ioctl 1

#> ls -l /dev/mem 
crw-r----- 1 root kmem 1, 1 nov.   5 17:49 /dev/mem

lshw -c video

  *-display               
       description: VGA compatible controller
       produit: Broadway XT [Mobility Radeon HD 5870]
       fabriquant: Hynix Semiconductor (Hyundai Electronics)
       identifiant matériel: 0
       information bus: pci@0000:01:00.0
       version: 00
       bits: 64 bits
       horloge: 33MHz
       fonctionnalités: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=fglrx_pci latency=0
       ressources: irq:50 mémoire:c0000000-cfffffff mémoire:d0020000-d003ffff portE/S:d000(taille=256) mémoire:d0000000-d001ffff

lspci

01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Broadway XT [Mobility Radeon HD 5870] (prog-if 00 [VGA controller])
	Subsystem: Micro-Star International Co., Ltd. Device 1054
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- SERR- <PERR- INTx-
	Latency: 0, Cache Line Size: 64 bytes
	Interrupt: pin A routed to IRQ 50
	Region 0: Memory at c0000000 (64-bit, prefetchable) [size=256M]
	Region 2: Memory at d0020000 (64-bit, non-prefetchable) [size=128K]
	Region 4: I/O ports at d000 [size=256]
	Expansion ROM at d0000000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: fglrx_pci
	Kernel modules: fglrx, radeon

**Comment by clbr** [comment]
> printf("use ioctl %u\n", use_ioctl);
> use ioctl 1

OK, it's trying to use the open-drivers-in-recent-kernels path for some
reason. Please try current master, I added an override option
(sudo radeontop -m).

The proprietary driver is fairly low priority, so automatically
detecting it won't be done by me, I couldn't even test it.

**Comment by adrenochrome25** [comment]
working perfectly with the '-m' switch, thanks :)
